name: ramp-stroke-cf
channels:
  - conda-forge
dependencies:
  - numpy
  - scikit-learn>=0.22
  - scipy
  - click
  - pandas
  - matplotlib

  # Extra requirements
  - tensorflow
  - pytorch
  - keras
  - lightgbm
  - nilearn
  - scikit-image>=0.18

  - pip
  - pip:
    - osfclient
    - ramp-workflow
    - ramp-utils
    - imbalanced-learn
    - git+https://www.github.com/keras-team/keras-contrib.git

    # Extra requirements pip
    - xgboost
    - catboost
