name: ramp-stroke
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scikit-learn>=0.22
  - scipy
  - click
  - pandas
  - matplotlib
  - wget
  - torch
  - bids
  - jupyterlab

  # Extra requirements
  - tensorflow-gpu<2.4
  - pytorch
  - keras
  - lightgbm
  - nilearn
  - scikit-image>=0.18

  - pip
  - pip:
    - osfclient
    - git+git://github.com/paris-saclay-cds/ramp-workflow
    - ramp-utils
    - imbalanced-learn
    - tensorflow-addons<0.12

    # Extra requirements pip
    - xgboost
    - catboost
